<?php

// $shipperAccount->json();
$data = [
    "meta"     => [],
    "data"     => [],
    "tracking" => [
        "id"              => "k6vv7u32k0o80lfccy00x02c",
        "created_at"      => "2023-03-17T09:48:36+00:00",
        "updated_at"      => "2023-03-17T09:48:36+00:00",
        "last_updated_at" => "2023-03-17T09:48:36+00:00",
        "tracking_number" => "48249CF9-6D77-4A04-8875-BF1E0113F612",
        "slug"            => "spring-gds",
        "active"          => true,
        "android"         => array(0),
        "custom_fields"   => array(5),
        "brandSlug"       => "sr_back_2",
        "brand_id"        => "6",
        "merchant_id"     => "84",
        "orderNumber"     => "order_number_0131234",
        "lastNameCode"    => "Gat",
        "customer_name"   => "Bill Gates",
        "delivery_time"   => 0,
        "destination_country_iso3"          => null,
        "courier_destination_country_iso3"  => null,
        "emails"                 => array(0),
        "expected_delivery"      => null,
        "ios"                    => array(0),
        "note"                   => null,
        "order_id"               => "order_number_0131234",
        "order_id_path"          => null,
        "order_date"             => "2022-12-10T03:41:24Z",
        "origin_country_iso3"    => null,
        "shipment_package_count" => null,
        "shipment_pickup_date"   => null,
        "shipment_delivery_date" => null,
        "shipment_type"          => null,
        "shipment_weight"        => null,
        "shipment_weight_unit"   => null,
        "signed_by"              => null,
        "smses"                  => array(0),
        "source"                 => "api",
        "tag"                    => "Pending",
        "subtag"                 => "Pending_001",
        "subtag_message"         => "Pending",
        "title"                  => "48249CF9-6D77-4A04-8875-BF1E0113F612",
        "tracked_count"                => 0,
        "last_mile_tracking_supported" => null,
        "language"                     => null,
        "unique_token"                 => "deprecated",
        "checkpoints"                  => array(0),
        "subscribed_smses"             => array(0),
        "subscribed_emails"            => array(0),
        "return_to_sender"             => false,
        "order_promised_delivery_date" => null,
        "delivery_type"                => null,
        "pickup_location"              => null,
        "pickup_note"                  => null,
        "courier_tracking_link"        => "https://www.spring-gds.com/",
        "first_attempted_at"           => null,
        "courier_redirect_link"        => null,
        "order_tags"                   => null,
        "order_number"                 => null,
        "aftership_estimated_delivery_date" => null,
        "destination_raw_location"     => null,
        "latest_estimated_delivery"    => null,
        "courier_connection_id"        => null,
        "shipment_tags"                => array(0),
        "next_couriers"                => array(0),
        "on_time_status"               => null,
        "on_time_difference"           => null,
        "tracking_account_number"      => null,
        "tracking_origin_country"      => null,
        "tracking_destination_country" => null,
        "tracking_key"                 => "GAT",
        "tracking_postal_code"         => null,
        "tracking_ship_date"           => null,
        "tracking_state"               => null
    ]
];


?>